### ISSUE TITLE
Allowed Controls is Incorrect on placeholder within the Dynamic Placeholder

### ISSUE THREAD

**Issue by dipskatta** [Fortis-Collection/dynamic-placeholders#3]
Hi There!
 I am using the MVC one based on several recommendations I thought this is the best way to move forward, but, running in to this situation where say a parent rendering has a Dynamic Placeholder which is loaded up with another supported rendering which has a placeholder.  Everything is working okay in this case except Allowed Controls for inner placeholder is pulling the parent (dynamic placeholder) allowed controls and not what is defined as allowed controls for inner placeholder.  I searched out there assuming there will be some input, but, looks like no one encountered this.  Now, if I drop dynamic placeholder and use regular one, Sitecore is doing well to get the correct allowed controls

**Comment by jammykam** [comment]
This used to work correctly and as expected in v1.1.0.1 of the module. Having upgraded a local project to 1.2.0.1 of the Nuget packages, this bug is introduced,

Steps to replicate:

1. Add Fortis DynamicPlaceholders.Mvc Nuget package (v1.1.0.1)
2. Create 2 different renderings with a dynamic placeholders defined (RenderingA and RenderingB)
3. Add some Allowed Controls to PlaceholderA, also add RenderingB to allow controls to be nested.
4. Add some different Allowed Controls to PlaceholderB 
5. In Experience Editor, add RenderingA and check renderings that are available in PlaceholderA
6. Insert RenderingB in the dynamic placeholder location from (5)
7. Check the renderings that are available to insert and note that they are different (and correct as you specified in 4 above)
8. Upgrade Nuget package to 1.2.0.1 and deploy the updates.
9. Repeat steps 5-7. Note that the Allowed Controls from PlaceholderA are listed even in PlaceholderB. The inner placeholder is incorrectly listing the controls of the parent wrapper.

**Comment by PratikSatikunvar** [comment]
We are facing this issue in V1.1.0.1 too.

**Comment by dipskatta** [comment]
Will create a PR shortly after by early next week.   We got the following scenarios worked out at this time. 
1. A simple sitecore placeholder
2. Sitecore placeholder inside a parent placeholder
3. Simple Dynamic Placeholder
4. A Dynamic placeholder inside a Dynamic placeholder
5. Sitecore placeholder inside dynamic placeholder.
The below is the one that is not working, we will address that by next week and I will create a PR here
6. If possible - Dynamic placeholder inside Sitecore placeholder

**Comment by rikin86** [comment]
I have fixed this issue by updating GetDynamicPlaceholderChromeData.cs and GetDynamicKeyAllowedRenderings.cs to use regex.Matches and then use last match. If you use regex.Match it will get first match which will be parent placeholder.

`if (string.Equals("placeholder", args.ChromeType, StringComparison.OrdinalIgnoreCase))
			{
				var placeholderKey = args.CustomData["placeHolderKey"] as string;
				var regex = new Regex(DynamicPlaceholders.PlaceholderKeyRegex.DynamicKeyRegex);
			    //var match = regex.Match(placeholderKey);
                var matches = regex.Matches(placeholderKey);

			    if (matches.Count > 0)
			    {
			        var match = matches.Cast<Match>().LastOrDefault();
			        if (match != null && match.Success && match.Groups.Count > 0)
			        {
			            var newPlaceholderKey = match.Groups[1].Value;

			            args.CustomData["placeHolderKey"] = newPlaceholderKey;

			            base.Process(args);

			            args.CustomData["placeHolderKey"] = placeholderKey;
			        }
			        else
			        {
			            base.Process(args);
                    }

                }
			
				else
				{
					base.Process(args);
				}
			}`

`  var matches = regex.Matches(currentPlaceholderKey);

            if(matches.Count < 1)
                return;
		    var match = matches.Cast<Match>().LastOrDefault();

            if (match != null && match.Success && match.Groups.Count > 0)
			{
				temporaryPlaceholderKey = match.Groups[1].Value;
			}
			else
			{
				return;
			}`

**Comment by dipskatta** [comment]
Yeah I did the same as well. 
But when we did that scenario #6 I mentioned above is not fixed.  We will need to see what to do to fix that scenario.  Did you have guys have scenario where Dynamic placeholder could be placed inside regular Sitecore placeholder?

**Comment by jasonbert** [comment]
This issue has been fixed by changing the Regex pattern to only match on the last occurrence. Please upgrade your package to 1.2.0.2.

https://regex101.com/r/z7vJXc/1

**Comment by mikemuggli** [comment]
Thank you all for the comments and @jasonbert thank you for the update. I believe there is still an issue with the regex when you have 2 placeholders with the same name in a single rendering. Or when you pass in the unique key parameter to the Html.Sitecore.DynamicPlaceholder("placeholder-key", "unique-key") method.

In either case it, the placeholder key has something appended to the end of the parent rendering id. For example, https://regex101.com/r/QJpeUd/1. This does not work.

Edit: I played around with the Regex and I think I might have one that will work with either when the unique key is appended or whether it is not. Feel free to try this one out.

https://regex101.com/r/eHcJfV/1

**Comment by ivnie** [comment]
Hi @mikemuggli  & @jasonbert 

I have the same issue when running 1.2.0.2. I'm using nested dynamic placeholders, both using the extension method: Html.Sitecore.DynamicPlaceholder("placeholder-key", "unique-key").

@mikemuggli Did you find a solution?

**Comment by mikemuggli** [comment]
Hi @ivnie. Yes, what worked for me was to modify the Regex in the config file. The Regex I ended up using is: 

https://regex101.com/r/eHcJfV/1

It will allow for unique key names with underscores, numbers, letters, white spaces and dashes. Which is good enough for me :)

**Comment by ivnie** [comment]
Hi @mikemuggli 

Thanks for the regex ;) I still had an issue where i didn't get any allowed renderings, because the placeholder key was resolved incorrectly. My placeholder key is "col-12", but was resolved to "col-12_". I'm not an regex expert, and it looks correct to me in the regex tester, so i decided to just add an "TrimEnd('_')" to newPlaceholderKey:

GetDynamicPlaceholderChromeData.Process:

        public override void Process(GetChromeDataArgs args)
        {
            Assert.ArgumentNotNull(args, "args");
            Assert.IsNotNull(args.ChromeData, "Chrome Data");

            if (string.Equals("placeholder", args.ChromeType, StringComparison.OrdinalIgnoreCase))
            {
                var placeholderKey = args.CustomData["placeHolderKey"] as string;
                var regex = new Regex(DynamicPlaceholders.PlaceholderKeyRegex.DynamicKeyRegex);
                var match = regex.Match(placeholderKey);

                if (match.Success && match.Groups.Count > 0)
                {
                    var newPlaceholderKey = match.Groups[1].Value.TrimEnd('_');

                    args.CustomData["placeHolderKey"] = newPlaceholderKey;

                    base.Process(args);

                    args.CustomData["placeHolderKey"] = placeholderKey;
                }
                else
                {
                    base.Process(args);
                }
            }
        }

**Comment by mikemuggli** [comment]
Hi @ivnie,

I think the Regex I posted was wrong. Sorry about that. This one should account for the underscore:

https://regex101.com/r/eHcJfV/1

Feel free to try that new Regex so that you don't have to modify the code for the pipeline.

Edit:
The comment box is stripping out characters in the Regex! Follow the link in this comment.
